.TH ROLL 6 2013-06-26
.SH NAME
roll \- Roll n dice with m sides.
.SH SYNOPSIS
.B roll
ndm
.SH DESCRIPTION
.B roll
simulates the result of rollin n dice, all with m sides.
It outputs the values for each dice separated by '+' followed by '=' and then the total value.
For example, roll 3d6 may result in 3+1+4=8
.SH RETURNS
The total value of the dice rolls.